// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AltTextController from "./alt_text_controller"
application.register("alt-text", AltTextController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ConsumedToggleController from "./consumed_toggle_controller"
application.register("consumed-toggle", ConsumedToggleController)

import DonutController from "./donut_controller"
application.register("donut", DonutController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SeasonTabsController from "./season_tabs_controller"
application.register("season-tabs", SeasonTabsController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ThumbnailFetcherController from "./thumbnail_fetcher_controller"
application.register("thumbnail-fetcher", ThumbnailFetcherController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
