version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/native/desktop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/native/desktop/src-tauri"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directory: "/native/ios/MediaInventory"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
